schemaVersion: 2.2.2
attributes:
  controller.devfile.io/storage-type: per-workspace
metadata:
  name: "sovereignty-paper"
  provider: Andrew Pitt
  displayName: Docs project
  description: Writing docs with Claude
  tags:
    - Docs
    - AI
    - Claude
  projectType: Markdown
  language: Markdown
projects:
  - name: "cost-management-exporter"
    git:
      remotes:
        origin: "https://github.com/pittar-rhdh/cost-management-exporter"
      checkoutFrom:
        revision: "main"
        remote: origin
components:
  - name: py
    container:
      image: registry.redhat.io/devspaces/udi-base-rhel10:latest
      args: ['tail', '-f', '/dev/null']
      mountSources: true
      cpuLimit: '4'
      cpuRequest: '1'
      memoryLimit: '8G'
      memoryRequest: '8G'
